import type { NextPage } from "next";
import Head from "next/head";
import Dummy from "../components/Dummy";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Dummy></Dummy>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
